### ISSUE TITLE
Workaround Safari 9 WebGL bug

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2989]
Not for 1.13 today.

Discussion: https://twitter.com/pjcozzi/status/638390320619761664

If we need to workaround this, replace all uses of `WebGLRenderingContext` with the actual constant, e.g.,
```
WebGLRenderingContext.LESS
```
becomes
```
0x0201 // WebGLRenderingContext.LESS
```

@lilleyse let's discuss.

**Comment by pjcozzi** [comment]
Should be fixed in https://bugs.webkit.org/show_bug.cgi?id=148449 but doesn't work yet in WebKit r189243 (02 September 2015).

**Comment by mramato** [comment]
Still broken in r189485 (September 8th).  If iOS 9 does get released tomorrow, I'm assuming Cesium will be broken.

**Comment by mramato** [comment]
iOS 9 will be released on September 16

**Comment by pjcozzi** [comment]
@lilleyse can you do this soon?  Unfortunately, we're going to need this workaround.  I think the best approach is to introduce a new static class like `ContextLimits` with _all _ the constants from the spec (perhaps called `ContextConstants` or `WebGLConstants`).

**Comment by mramato** [comment]
@pjcozzi should we make an announcement on the mailing list ahead of time?  No need to be too negative on Safari, but just mention that it will break existing Cesium apps and people shouldn't upgrade iOS or Safari if they need Cesium until we release a workaround (or Apple releases a fix).

**Comment by lilleyse** [comment]
Yes I can start working on this today.

**Comment by lilleyse** [comment]
There are many areas that already hard code constants, like https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/BufferUsage.js#L11-L14

Should I modify all of these to use the new constants class as well?

**Comment by pjcozzi** [comment]
> Should I modify all of these to use the new constants class as well?

Yes, those are very old...before I even knew of `WebGLRenderingContext`.

> @pjcozzi should we make an announcement on the mailing list ahead of time?

Yes, go ahead.
