### ISSUE TITLE
Problems with terrainExaggeration parameter in version > v.1.16

### ISSUE THREAD

**Issue by jacmendt** [AnalyticalGraphicsInc/cesium#3676]
I expected some problems with the the `terrainExaggeration` parameter in cesium versions >= 1.17. I used a `terrainExaggeration` value of 4.0 in version 1.16 and it works for me. In newer versions, my terrain / imagery isn't display anymore if zooming to higher zoom levels. My area of interest was europe.

I reproduced the error running the [sandbox application](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) with this code: 

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainExaggeration: 4.0
});

var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : '//assets.agi.com/stk-terrain/world'
});
viewer.terrainProvider = terrainProvider;
```

**Comment by mramato** [comment]
Thanks @jacmendt, this is a known issue that we definitely plan on fixing for our next release (April 1st).

Since this is a duplicate of #3607, I'm going to close this issue.  Thanks again.

**Comment by pjcozzi** [comment]
@jacmendt this was fixed in #3734 and will be released in Cesium 1.20 on April 1.

**Comment by jacmendt** [comment]
@pjcozzi i tested today the new Cesium version 1.20 and the error stil exists. I also tested again the `sandbox application` described above and could reproduced the error, but I'm not sure if the `sandbox application` is also using the latest cesium version.

**Comment by mramato** [comment]
I can confirm that this is still an issue, but only in specific portions of the Earth (which is why it was probably missed).  Use the original sample code and zoom to `Dancy, Eure-et-Loir, France` in the Geocoder and you'll see it.

@bagnell can you take a look at this?

**Comment by pjcozzi** [comment]
Thanks for the report, we have a few other things on our plate, but we'll try to look at this before the next release.

**Comment by pjcozzi** [comment]
@bagnell can you take a quick look to see if this is small enough in scope to make 1.21 on Monday?
