### ISSUE TITLE
Outline around label's characters and billboards in clustering demo

### ISSUE THREAD

**Issue by rutsky** [AnalyticalGraphicsInc/cesium#4525]
I often (but not always) see gray border around characters and billboards in [clustering demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clustering.html&label=Showcases):

![2016-10-25_21 55 37_1](https://cloud.githubusercontent.com/assets/46573/19699974/751484a4-9b06-11e6-9841-43f94b3b2908.png)

![2016-10-25_22 01 01_1](https://cloud.githubusercontent.com/assets/46573/19700111/07ed2d44-9b07-11e6-93d3-f4a7fb762161.png)

Tested on Ubuntu 16.04 with Firefox 51.0a2 and Chromium 53.0.2785.143.

**Comment by rutsky** [comment]
Same issue on [labels demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Labels.html&label=Showcases):

![2016-10-25_22 07 40_1](https://cloud.githubusercontent.com/assets/46573/19700326/e48bf1fe-9b07-11e6-9878-db0c34c83699.png)

![2016-10-25_22 07 29_1](https://cloud.githubusercontent.com/assets/46573/19700329/e8cb2f3c-9b07-11e6-9cbb-47fba9fbe884.png)

![2016-10-25_22 07 21_1](https://cloud.githubusercontent.com/assets/46573/19700331/eba2f528-9b07-11e6-81f7-568ac7dabb6f.png)

**Comment by rutsky** [comment]
This is not reproduced when I use integrated graphics from Intel on the same Linux machine.

**Comment by rutsky** [comment]
Might be related: #2130

**Comment by rutsky** [comment]
@mramato since you've seen similar issue as you noted in [this](https://github.com/AnalyticalGraphicsInc/cesium/issues/2130#issuecomment-106612931) comment, maybe you can give some hints what is the reasons of this bug and how can it be resolved?

**Comment by mramato** [comment]
@bagnell believes this may be related to texture coordinates being slightly off for billboards. The odd part is that it only happens on some systems, so we could have a case of undefined behavior somewhere or a rounding issue.  Billboard collection (particular the shaders) would be the first place I look to try and debug this.

**Comment by elFerZur** [comment]
I have the same problem with billboards, of any type (gif, png, svg). Tested on Windows 10 with Firefox 49 and Intel graphics card.

![billboard_01](https://cloud.githubusercontent.com/assets/23243268/19976757/5d6149d6-a1f1-11e6-9b1d-79fc9563149c.png)
![billboard_02](https://cloud.githubusercontent.com/assets/23243268/19976761/5f63b14c-a1f1-11e6-834f-f6c5e214af16.png)

**Comment by emackey** [comment]
@rutsky @elFerZur Can either of you re-test this with master now that #4675 is merged?  Thanks.

**Comment by rutsky** [comment]
@emackey I can't reproduce with borders described in this bugreport, thanks!

![2016-11-29_21 08 40_1](https://cloud.githubusercontent.com/assets/46573/20722534/6847a3c4-b680-11e6-8d00-2a943e9e9c10.png)



Not sure is it related, but in master I don't see labels in clustering demo:

![2016-11-29_21 06 08_1](https://cloud.githubusercontent.com/assets/46573/20722462/28ee9a02-b680-11e6-929e-1dae9bdf485f.png)

**Comment by bjbrewster** [comment]
I believe this last issue of missing labels is related to https://github.com/AnalyticalGraphicsInc/cesium/issues/4919

**Comment by hpinkos** [comment]
Also reported by @dominicrico in #6006

**Comment by mramato** [comment]
@bagnell is this just a clamping issue?  I didn't realize this bug was still around.

**Comment by dominicrico** [comment]
Any update or workaround here?

**Comment by emackey** [comment]
@dominicrico I had believed this was fixed with #4675, and was left open by accident (or due to mentioning of missing labels, although that should have been a separate issue).

I tried a 100x200 billboard in Firefox and couldn't reproduce the black borders.  Can you send us a reproduce case?

**Comment by mramato** [comment]
@emackey it looks like people are still having issues with the latest Cesium, either this was re-introduced or is cropping up in a different form.

Does anyone have a simple Sandcastle that shows this issue?

**Comment by rutsky** [comment]
@mramato 
> Does anyone have a simple Sandcastle that shows this issue?

I see this bug in  [clustering demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clustering.html&label=Showcases) from the original bug report on Firefox 57.0.1 on Ubuntu 16.04 with GeForce GT 640M and Nvidia drivers 340.102 (thought it doesn't appear with all billboards):
 
![_270](https://user-images.githubusercontent.com/46573/34588040-34fda4a2-f1ab-11e7-8031-1712657d7af8.png)

**Comment by EarMaster** [comment]
Any news on this?

**Comment by emackey** [comment]
@EarMaster I can't reproduce this under Windows, and I don't have a Linux system to test.  What system, browser, graphics card, and demo do you see it on?

**Comment by hpinkos** [comment]
Also see example in #7703

**Comment by hpinkos** [comment]
Appears in firefox on the callback property demo https://github.com/AnalyticalGraphicsInc/cesium/issues/8344#issuecomment-548894898

**Comment by ggetz** [comment]
Also reported in https://github.com/CesiumGS/cesium/issues/12861

**Comment by donmccurdy** [comment]
I think I've found at least one cause behind this — the billboard texture atlas creates a border around the edges of the atlas, but not between images within the atlas. Probably the border should be between images as well? PR in progress, which fixes the square outline around pins from https://github.com/CesiumGS/cesium/issues/4525#issuecomment-379767951.
