### ISSUE TITLE
DistanceDisplayCondition point in the middle of the Viewer

### ISSUE THREAD

**Issue by tangtony** [AnalyticalGraphicsInc/cesium#7557]
I've come across a strange issue that seems to only affects Linux. In the Sandcastle example, there are a bunch of points on the globe with distanceDisplayCondition configured. The points are configured to be visible only above 500000, and should be hidden below that.

On my Windows 10 PC with the same browser version, everything seems to work fine. On my CentOS PC though, there seems to be a single point visible in the center of the viewer after zooming past 500000. It's a bit hard to explain so I've attached some pictures below. Both PCs have Nvidia graphics cards (one is a 1060 and the other is a 980).

Before zooming past 500000:
![before](https://user-images.githubusercontent.com/5085394/52587664-822b4280-2e08-11e9-9191-c69734c396da.PNG)

After zooming past 500000 (on Windows):
![after windows](https://user-images.githubusercontent.com/5085394/52587662-80617f00-2e08-11e9-99e0-afa3049da5e3.PNG)

After zooming past 500000 (on CentOS):
![after linux](https://user-images.githubusercontent.com/5085394/52587655-7c356180-2e08-11e9-9ada-e50a50ab17f2.png)

Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dVLva9swEP1XhL/UZpmcMApb6oZ1+TEGWxrmMfbBUBTrkorJUpDkpNno/96TXTu2xw5/uHv33jufpCMz5CjgBIbcEgUnMgcryoL+rLDwKq/KuVaOCQXmKrrJVM2nNgcFlMO23KeP+rQyrAC7AZNCrhVHO2dK8HQccdBCOYtYT3swohBOHMFSxnnYGb/x/E3TnmspIXdCqzCKGkfxBDIVfwBNJ4hlaqcNCX1LarUXruS+9XbyfnzTQRIyAN6gPCJ/M0UwLhbMtQ4fPL+pE9Ire2of9aLVOh207ljhVyDTZsk5Mw4zpt7RndHFAvYGwIbtv43aOdFo4NUuP73kA47NmYRP54Wwjqkcpt3bXQMzK2ZSpDATXo99jMg1fuPXfDIcyV990O8g2RlfBK/W6fku/kNqR6zLYovX/+3u10N6t1o+fFn/WH5efo8us579BVdJpp6DUZBYd5Ywq7GPojho40hpZEhp7KDAMXiG8bbMf4OjubVensSNKOHiSAS/zYLBQ84CkktmLXZ2pazOLwtmSYz8nkxqxoXa3x/B4EKe8jiZfa1BSmkSY/mvymktt8x0HF8A

Browser: Chrome 71.0.3578.98 (Official Build) (64-bit)

Operating System: CentOS 7.6.1810

**Comment by hpinkos** [comment]
Thanks @tangtony!  This sounds like it might be related to #7031

We've been having trouble reproducing this one which has made it tough to fix.  Thank you so much for including the Sandcastle example!  @mramato can you try that out on your linux machine?

**Comment by mramato** [comment]
I can absolutely reproduce this on Linux (Nvidia) and also via Cesium ion (the tileset position tool ends up with a large phantom point).

**Comment by tangtony** [comment]
I forgot to mention this before, but I had messed around with this a few months ago and I had written down that v384.111 was the last Nvidia driver without this problem. I don't have a free machine to verify this again though.

**Comment by mramato** [comment]
Fixed via above PR

**Comment by tangtony** [comment]
The above PR does not fix this issue on my CentOS machine. Using the same Sandcastle example I can still reproduce the issue.

**Comment by mramato** [comment]
Looks like this is indeed back.  @OmarShehata didn't you fix an issue with how we hide points vs alpha or something recently with a shader? @lilleyse any ideas?

1. Run http://localhost:8080/Apps/Sandcastle/index.html?src=Distance%20Display%20Conditions.html&label=All
2. Switch to Point and Model and zoom in.
3. Instead of the point switching off, it jumps to the center of the screen

![image](https://user-images.githubusercontent.com/1495196/68304965-d51ee700-0074-11ea-909f-ff6295907358.png)

**Comment by mramato** [comment]
Since this is a regression and impacts a lot of use cases, I would like to see it fixed for 1.64 (but hopefully in master sooner).

**Comment by OmarShehata** [comment]
There is no regression here. Brandon's PR https://github.com/AnalyticalGraphicsInc/cesium/pull/8054 fixed this hidden point issue https://github.com/AnalyticalGraphicsInc/cesium/issues/8043 which is still fixed as of 1.63. 

It looks like you closed this issue https://github.com/AnalyticalGraphicsInc/cesium/issues/7557#issuecomment-522019636 without verifying that it was fixed by that PR. This most likely requires the same type of fix just applied in this distance display condition shader.

**Comment by mramato** [comment]
My bad, I guess I didn't realize they were different issues.  Sounds like we know how to fix it, so I'll leave this open as a next release issue.
